// Generated by https://quicktype.io

export interface DashboardSummaryResponse {
    numberOfOrders:         number;
    paidOrders:             number;
    noPaidOrders:           number;
    numberOfClients:        number;
    numberOfProducts:       number;
    productWithNoInventory: number;
    lowInventary:           number;
}
